#include <iostream>
using namespace std;

int main() {
    cout << "Hello, World!" << endl; //1.cout sends text to your scren as output
    cout << "Welcome to C++ Programming." << endl;
    cout << "Department of Computer Engineering," << endl; //2. operator pushes data to the stream (e.g<iostream>>
    cout << "University of Uyo." << endl;
    cout << "2025/2026 Academic Session." << endl; //3. cout statement always ends with a semi colomn ;
    return 0;
    
}